defaults:  
  - _self_  
  - override hydra/launcher: submitit_slurm
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled    

task: 1

  
hydra:  
  output_subdir: null  
  run:  
    dir: .
  launcher:
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: ${hydra.sweep.dir}/.submitit/%j
    name: Pythia
    timeout_min: 60  # Reduced timeout for testing
    gpus_per_node: 1
    tasks_per_node: 1
    nodes: 1
    mem_gb: 16
    cpus_per_task: 4
    partition: qdgx
    qos: null  # Add if your cluster requires it
    account: OPEN-32-32
    comment: null
    setup:
      - module load CUDA  # Add any required modules
    additional_parameters:
      mail-type: FAIL
      mail-user: ${oc.env:USER}@example.com