data:
  datapath: data
  specific_datapath: sos/
  train_file: sos/train1_b4_t30_n200000_dfs.json
  val_target_file: sos/val_target1_b4_t30_n200000_dfs.json
  val_file: sos/val1_b4_t30_n200000_dfs.json
  tokenizer_path: data/sos/tokenizer.json
  num_train: 2e5
  num_workers: 4

model:
  model_name: "GPT2"
  n_layers: 16
  n_heads: 16
  n_embed: 768
  dropout: 0.1
  n_hidden: 1024
  block_size: 4096
  vocab_size: 410
  bias: True

train:
  batchsize: 12
  max_epochs: 20
  grad_clip: 1.0
  weight_decay: 0.1
  learning_rate: 3e-4
  patience: 4
  betas: [0.9, 0.95]

other:
  ckpt: "ckpt.pt"