data:
  datapath: data.pkl
  num_workers: 4

model:
  model_name: "GPT2"
  n_layers: 12
  n_heads: 12
  n_embed: 768
  dropout: 0.1
  n_hidden: 256
  block_size: 1024
  vocab_size: 120
  bias: True

train:
  batchsize: 128
  max_epochs: 100
  grad_clip: 1.0
  weight_decay: float = 0.1
  learning_rate: float = 3e-4
  patience: int = 10
  betas: [0.9, 0.95]

other:
  ckpt: "ckpt.pt"