data:
  datapath_train: /mnt/raid/data/rl_basic_transformer/data/train.pkl
  datapath_val: /mnt/raid/data/rl_basic_transformer/data/test.pkl
  tokenizer_path: /mnt/raid/data/rl_basic_transformer/tokenizer/tokenizer.json
  num_workers: 4

model:
  model_name: "GPT2"
  n_layer: 6
  n_head: 4
  n_embd: 32
  dropout: 0.1
  n_hidden: 256
  block_size: 1024
  vocab_size: 120
  bias: True

train:
  batchsize: 128
  max_epochs: 100
  grad_clip: 1.0
  weight_decay: 0.1
  learning_rate: 3e-4
  patience: 10
  betas: [0.9, 0.95]

other:
  ckpt: "ckpt.pt"