defaults:  
  - _self_  
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled  
  
hydra:  
  output_subdir: null  
  run:  
    dir: .

tok_data:
  train_file: "../data/sos/train1_b4_t30_n500000_dfs.json"
  val_target_file: "../data/sos/val_target1_b4_t30_n500000_dfs.json"
  val_file: "../data/sos/val1_b4_t30_n500000_dfs.json"
  tokenizer_path: "../tokenizer/tokenizer.json"

data:
  datapath: data
  train_file: "sos/train1_b4_t30_n500000_dfs.json"
  val_target_file: "sos/val_target1_b4_t30_n500000_dfs.json"
  val_file: "sos/val1_b4_t30_n500000_dfs.json"
  num_train: 2e5
  num_val: 1e3
  num_workers: 64
  filtered_output: "../data/sos_filtered"

model:
  block_size: 4096
  vocab_size: 410
  padded_vocab_size: 410
  bos_id: 404
  eos_id: 408
  checkpoint_dir: "model/${dl_model.full_path}"
  tokenizer_path: "model/${dl_model.full_path}"