defaults:  
  - _self_  
  - override hydra/launcher: submitit_slurm
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled    
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
  launcher:
    name: Pythia
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: logs/Pythia-single/%j
    timeout_min: 2880
    gres: "gpu:1"
    tasks_per_node: 1
    nodes: 1
    partition: "qdgx"
    account: "OPEN-32-32"
    comment: null
    constraint: null
    max_num_timeout: 0

tok_data:
  train_file: "../data/sos_filtered/train1_b4_t30_n2000000_dfs_filtered.json"
  val_target_file: "../data/sos_filtered/test1_b4_t30_n2000000_dfs_filtered.json"
  val_file: "../data/sos_filtered/val1_b4_t30_n2000000_dfs_filtered.json"
  tokenizer_path: "tokenizer/tokenizer.json"

data:
  datapath: data
  train_file: "sos_filtered/train1_b4_t30_n2000000_dfs_filtered.json"
  val_target_file: "sos_filtered/test1_b4_t30_n2000000_dfs_filtered.json"
  val_file: "sos_filtered/val1_b4_t30_n2000000_dfs_filtered.json"
  num_train: 2e5
  num_val: 512
  num_workers: 64

model:
  name: dgx-Pythia-${model.n_layer}-${model.n_head}-${model.n_embd}-dfs-increasing
  batch_size: 48
  accumulate_grad_batches: 1
  block_size: 4096
  epochs: 100
  n_layer: 6
  n_head: 4
  n_embd: 128
  vocab_size: 420
  padded_vocab_size: 420
  bos_id: 410
  eos_id: 414

eval:
  num_examples: 128
  batch_size: 64
  eval_interval: 1 # epoch
  results_dir: "data/eval_results/${model.name}"

convert_hf:
  in_path: "temp/${model.name}"
  out_path: "temp/hf_${model.name}"