defaults:  
  - _self_  
  - override hydra/launcher: submitit_slurm
  - override hydra/hydra_logging: disabled  
  - override hydra/job_logging: disabled    
  
hydra:  
  output_subdir: null  
  run:  
    dir: .
  launcher:
    name: Pythia
    _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
    submitit_folder: logs/Pythia-single/%j
    timeout_min: 2880
    gres: "gpu:1"          
    tasks_per_node: 1
    nodes: 1
    partition: "qgpu"
    account: "OPEN-30-4"
    comment: null
    constraint: null
    max_num_timeout: 0

tok_data:
  train_file: "../data/sos_filtered/train1_b4_t30_n500000_dfs_filtered.json"
  val_target_file: "../data/sos_filtered/val_target1_b4_t30_n500000_dfs_filtered.json"
  val_file: "../data/sos_filtered/val1_b4_t30_n500000_dfs_filtered.json"
  tokenizer_path: "tokenizer/tokenizer.json"

data:
  datapath: data
  train_file: "sos_filtered/train1_b4_t30_n500000_dfs_filtered.json"
  val_target_file: "sos_filtered/val_target1_b4_t30_n500000_dfs_filtered.json"
  val_file: "sos_filtered/val1_b4_t30_n500000_dfs_filtered.json"
  num_train: 2e5
  num_val: 512
  num_workers: 16

model:
  name: "Pythia-${model.n_layer}-${model.n_head}-${model.n_embd}-dfs"
  batch_size: 32
  accumulate_grad_batches: 1
  block_size: 4096
  epochs: 100
  n_layer: 24
  n_head: 8
  n_embd: 256
  vocab_size: 410
  padded_vocab_size: 410
  bos_id: 404
  eos_id: 408

eval:
  num_examples: 512
  batch_size: 64
  eval_interval: 1 # epoch
  results_dir: "data/eval_results/${model.name}"

convert_hf:
  in_path: "temp/${model.name}"
  out_path: "temp/hf_${model.name}"

cur:
  max_epochs: 5