defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: grid

hydra:
  sweeper:
    direction: maximize
    study_name: sphere
    storage: null
    n_trials: 4
    n_jobs: 1
    params:
      # model.n_iters: choice(3,2,1)
      # model.n_embd: choice(96,128,256)

data:
  batch_size: 64
  num_workers: 32
  dataset_path: "/mnt/raid/data/Hyner_Petr/rl/rl_basic_transformer/NN/new_data_only_triples_nn_old.pkl"
train:
  learning_rate: 3.0e-4
  num_epochs: 100
  log_every: 100
  lr: 5.0e-4
  wdecay: 1.2e-6
model:
  vocab_size: 106
  block_size:  20
  n_iters: 2
  n_head: 1
  n_embd: 96
  n_hidden: 16
  dropout: 0.0
  bias: True
  init_bottleneck_by_last: True